import type { Metadata } from "next";
import { fonts } from "../lib/fonts/fonts";
import { Providers } from "../lib/providers/providers";

import "./globals.css";

export const metadata: Metadata = {
  title: "Map App using Google Maps API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fonts.rubik.variable}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
